export const permissionList = {
  location: {
    title: "Lokasi",
    apiUrl: "/location",
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  jobPosition: {
    title: "Jabatan",
    apiUrl: "/job-position",
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  users: {
    title: "Karyawan",
    apiUrl: "/user",
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  userPermissions: {
    title: "User permissions",
    apiUrl: "",
    create: false,
    read: null,
    update: null,
    delete: null,
  },
  categoryStock: {
    title: "Category stock",
    apiUrl: "/category-stock",
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  categoryTreatment: {
    title: "Category treatment",
    apiUrl: "/category-treatment",
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  categoryProduct: {
    title: "Category product",
    apiUrl: "/category-product",
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  unit: {
    title: "Satuan",
    apiUrl: "/unit",
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  product: {
    title: "Produk",
    apiUrl: "/products",
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  productBundle: {
    title: "Produk bundle",
    apiUrl: "/product-bundle",
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  inventory: {
    title: "Inventory",
    apiUrl: "/inventory",
    create: null,
    read: false,
    update: false,
    delete: null,
  },
  stockTransfer: {
    title: "Stock transfer",
    apiUrl: "/stock-transfer",
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  treatment: {
    title: "Treatment",
    apiUrl: "/treatment",
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  customer: {
    title: "Customer",
    apiUrl: "/customer",
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  purchase: {
    title: "Pembelian",
    apiUrl: "/purchase",
    create: false,
    read: false,
    update: null,
    delete: null,
  },
  queue: {
    title: "Antrian",
    apiUrl: "/queue",
    create: false,
    read: false,
    update: null,
    delete: false,
  },
  medicalRecords: {
    title: "Rekam medis",
    apiUrl: "/medical-records",
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  consultation: {
    title: "Konsultasi",
    apiUrl: "/consultation",
    create: false,
    read: false,
    update: null,
    delete: null,
  },
  selling: {
    title: "Penjualan",
    apiUrl: "/selling",
    create: false,
    read: false,
    update: null,
    delete: null,
  },
  transactionHistory: {
    title: "History transaction",
    apiUrl: "/transaction-history",
    create: null,
    read: false,
    update: null,
    delete: null,
  },
  discount: {
    title: "Discount",
    apiUrl: "/discount",
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  sellingStockClinic: {
    title: "Penjualan stok klinik",
    apiUrl: "/selling-stock-clinic",
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  feeReport: {
    title: "Laporan fee",
    apiUrl: "/reports/fee",
    create: null,
    read: false,
    update: null,
    delete: null,
  },
  incomeReport: {
    title: "Laporan pendapatan",
    apiUrl: "/reports/income",
    create: null,
    read: false,
    update: null,
    delete: null,
  },
  attendanceReport: {
    title: "Laporan absensi",
    apiUrl: "/reports/attendance",
    create: null,
    read: false,
    update: null,
    delete: null,
  },
  customerNextVisit: {
    title: "Kunjungan selanjutnya",
    apiUrl: "",
    create: null,
    read: false,
    update: null,
    delete: null,
  },
  employeeLeavePermit: {
    title: "Cuti & izin karyawan",
    apiUrl: "",
    create: null,
    read: false,
    update: null,
    delete: null,
  },
  stockOpname: {
    title: "Stock Opname",
    apiUrl: "",
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  crmDashboard: {
    title: "CRM dashboard",
    apiUrl: "",
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  posDashboard: {
    title: "POS dashboard",
    apiUrl: "",
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  stockManagementDashboard: {
    title: "Stock management dashboard",
    apiUrl: "",
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  province: {
    title: "Provinsi",
    apiUrl: "",
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  citiesDistricts: {
    title: "Kota/Kabupaten",
    apiUrl: "",
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  subDistricts: {
    title: "Kelurahan",
    apiUrl: "",
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  assets: {
    title: "Assets",
    apiUrl: "",
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  employeeInOutReport: {
    title: "Laporan Karyawan In Out",
    apiUrl: "",
    create: null,
    read: false,
    update: null,
    delete: null,
  },
  queueSalon: {
    title: "Antrian",
    apiUrl: "",
    create: null,
    read: false,
    update: null,
    delete: null,
  },
  sellingProductSalon: {
    title: "Penjualan",
    apiUrl: "",
    create: null,
    read: false,
    update: null,
    delete: null,
  },
  customerSalon: {
    title: "Customer Salon",
    apiUrl: "",
    create: null,
    read: false,
    update: null,
    delete: null,
  },
  posSalonDashboard: {
    title: "Dashboard POS Salon",
    apiUrl: "",
    create: null,
    read: false,
    update: null,
    delete: null,
  },
  paymentMethod: {
    title: "Metode pembayaran",
    apiUrl: "",
    create: null,
    read: false,
    update: null,
    delete: null,
  },
  expenseCategories: {
    title: "Kategori pengeluaran",
    apiUrl: "",
    create: null,
    read: false,
    update: null,
    delete: null,
  },
  expenses: {
    title: "Pengeluaran",
    apiUrl: "",
    create: false,
    read: false,
    update: false,
    delete: false,
  },
  treatmentReport: {
    title: "Laporan treatment",
    apiUrl: "",
    create: null,
    read: false,
    update: null,
    delete: null,
  },
  disciplinaryActionEmployee: {
    title: "ST/SP Karyawan",
    apiUrl: "",
    create: null,
    read: false,
    update: null,
    delete: null,
  },
  disciplinaryAction: {
    title: "ST/SP",
    apiUrl: "",
    create: null,
    read: false,
    update: null,
    delete: null,
  },
}
